import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Mycontext from "@/contextdata/Mycontext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await fetch('https://keen-keeper-project-iota.vercel.app/data.json',{
    cache: 'no-store'
  });
  const data = await response.json();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col !bg-white">
        <Mycontext data={data}> 
          <ToastContainer></ToastContainer>
          <Navbar></Navbar>
          {children}
        </Mycontext>
      </body>
    </html>
  );
}
